name: documentation
channels:
- defaults
dependencies:
- alabaster
- asn1crypto
- babel
- ca-certificates
- certifi
- cffi
- chardet
- commonmark
- cryptography
- docutils
- future
- idna
- imagesize
- jinja2
- libedit
- libffi
- libgcc-ng
- libstdcxx-ng
- markupsafe
- matplotlib
- ncurses
- numpy
- numpydoc
- openssl
- pip
- pycparser
- pygments
- pyopenssl
- pysocks
- python
- pytz
- readline
- requests
- setuptools
- six
- snowballstemmer
- sphinx
- sphinxcontrib
- sphinxcontrib-websupport
- sqlite
- tk
- typing
- urllib3
- wheel
- xz
- zlib
- pip:
  - recommonmark==0.4.0
  - example